# https://maplibre.org/martin/30-config-file.html

# Connection keep alive timeout [default: 75]
keep_alive: 75

# The socket address to bind [default: 0.0.0.0:3000]
listen_addresses: '0.0.0.0:3000'

postgres:
  - connection_string: $DATABASE_URL
    default_srid: 4326
    pool_size: 20
    auto_bounds: skip
    minzoom: 9
    maxzoom: 18
    auto_publish:
      from_schemas:
        - public
        - spacerat
      tables:
        source_id_format: 'table.{table}.{column}'
      functions:
        source_id_format: '{schema}.{function}'
  - connection_string: $MAPS_DATABASE_URL
    default_srid: 4326
    pool_size: 20
    auto_bounds: quick
    minzoom: 5
    maxzoom: 20
    auto_publish:
      from_schemas:
        - public
      tables:
        source_id_format: 'map.{table}.{column}'
      functions:
        source_id_format: 'map.{schema}.{function}'


# Publish MBTiles files
mbtiles:
  paths:
    # scan this whole dir, matching all *.mbtiles files
    - /tiles
