version: "3"


volumes:
  solr_data:

services:

  ckan:
    container_name: ${CKAN_CONTAINER_NAME}
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    networks:
      - ckannet
      - solrnet
      - redisnet
    env_file:
      - .env
    depends_on:
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "0.0.0.0:${CKAN_PORT_HOST}:${CKAN_PORT}"
    volumes:
      - /data/ckan:/var/lib/ckan
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5000"]
    
  datapusher-plus:
    container_name: datapusher-plus
    build:
      context: ./datapusher-plus
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:${DATAPUSHER_PORT_HOST}:8800"
    networks:
      - ckannet
    links:
      - ckan
    depends_on:
      - ckan
    environment:
      - DATASTORE_DB
      - DATAPUSHER_PASSWORD
      - DATAPUSHER_JOBS_PASSWORD
    env_file:
      - ./datapusher-plus/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO", "/dev/null", "http://localhost:8800" ]

  solr:
    container_name: ${SOLR_CONTAINER_NAME}
    networks:
      - solrnet
    image: ckan/ckan-solr:${SOLR_IMAGE_VERSION}
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:${REDIS_VERSION}
    networks:
      - redisnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]

  tiles:
    container_name: ${MARTIN_CONTAINER_NAME}
    build:
      context: martin/
    platform: linux/x86_64
    networks:
      - ckannet
    restart: unless-stopped
    ports:
      - "0.0.0.0:${MARTIN_PORT_HOST}:3000"
    environment:
      - "DATABASE_URL=${CKAN_DATASTORE_READ_URL}"
    healthcheck:
      test: [ "CMD", "wget", "-qO", "/dev/null", "http://localhost:3000/solr/" ]

networks:
  ckannet:
  solrnet:
    internal: true
  redisnet:
    internal: true
