#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE datapusher LOGIN PASSWORD '$DATAPUSHER_PASSWORD';
  GRANT CREATE, CONNECT, TEMPORARY ON DATABASE datastore TO datapusher;
  GRANT USAGE ON SCHEMA public to datapusher;
  ALTER ROLE datapusher WITH SUPERUSER;

  CREATE ROLE datapusher_jobs NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '$DATAPUSHER_JOBS_PASSWORD';
  CREATE DATABASE datapusher_jobs WITH OWNER datapusher_jobs ENCODING UTF8;
EOSQL